### ISSUE TITLE
run webpack an issue came out

### ISSUE THREAD

**Issue by rellame** [starkwang/react-redux-es6-quickstart#1]
when In run webpack,the console said"ERROR in Entry module not found:ERROR:Cannot resolve module 'index.jsx' in 'D:\desktop/test/redux-test'.It cames out because the entry file'route is wrong,I just wrote a absolute route,so webpack can't find it.So I modified it with a relative route, it works.

**Comment by Happy-xiaoxi** [comment]
entry文件路径应该是 ./entry.jsx ,教程里面少些了 "./"

**Comment by starkwang** [comment]
fixed
